apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: microservices
spec:
  features:
    - name: SchedulerReminders
      enabled: false

  tracing:
    samplingRate: '1'

  metric:
    enabled: true

  mtls:
    enabled: true
    workloadCertTTL: '24h'
    allowedClockSkew: '15m'
    controlPlaneTrustDomain: 'cluster.local'
    sentryAddress: 'dapr-sentry.dapr-system.svc.cluster.local:80'

  accessControl:
    defaultAction: allow
    trustDomain: 'public'
